"""add user created at

Revision ID: 43e962ece882
Revises: e0a3c2332dc7
Create Date: 2026-08-25 14:06:18.653990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e962ece882'
down_revision: Union[str, Sequence[str], None] = 'e0a3c2332dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )
    # ### end Alembic commands ###

    op.execute(
        """
        UPDATE users
        SET created_at = CURRENT_TIMESTAMP
        WHERE created_at IS NULL
        """
    )

    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        )

def downgrade() -> None:
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("created_at")
