"""rework adaptation process

Revision ID: 59f0d31cba95
Revises: 47dfaa9d371b
Create Date: 2026-09-10 13:02:48.002183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f0d31cba95'
down_revision: Union[str, Sequence[str], None] = '47dfaa9d371b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptation_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('position_category', sa.Enum('line_staff', 'specialist', 'manager', 'head', name='position_category'), nullable=False),
    sa.Column('stage_1_start_offset_days', sa.Integer(), nullable=False),
    sa.Column('stage_1_duration_days', sa.Integer(), nullable=False),
    sa.Column('stage_2_red_offset_days', sa.Integer(), nullable=False),
    sa.Column('stage_2_normal_offset_days', sa.Integer(), nullable=False),
    sa.Column('stage_2_duration_days', sa.Integer(), nullable=False),
    sa.Column('stage_3_red_offset_days', sa.Integer(), nullable=False),
    sa.Column('stage_3_normal_offset_days', sa.Integer(), nullable=False),
    sa.Column('stage_3_duration_days', sa.Integer(), nullable=False),
    sa.Column('total_deadline_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_adaptation_policy_dates'),
    sa.CheckConstraint('stage_1_start_offset_days >= 0 AND stage_1_duration_days > 0 AND stage_2_red_offset_days >= 0 AND stage_2_normal_offset_days >= 0 AND stage_2_duration_days > 0 AND stage_3_red_offset_days >= 0 AND stage_3_normal_offset_days >= 0 AND stage_3_duration_days > 0 AND total_deadline_days > 0', name='ck_adaptation_policy_positive_days'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_category', 'effective_from', name='uq_adaptation_policy_category_effective_from')
    )
    op.create_index(op.f('ix_adaptation_policies_position_category'), 'adaptation_policies', ['position_category'], unique=False)
    op.create_table('adaptation_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('introductory_process_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Completed', 'Cancelled', name='adaptation_process_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['introductory_process_id'], ['introductory_process.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['adaptation_policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_processes_introductory_process_id'), 'adaptation_processes', ['introductory_process_id'], unique=True)
    op.create_index(op.f('ix_adaptation_processes_policy_id'), 'adaptation_processes', ['policy_id'], unique=False)
    op.create_table('adaptation_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adaptation_process_id', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('planned_end_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('method', sa.Enum('in person', 'on portal', 'a phone call', 'yandex form', name='method_execution_adaptation'), nullable=True),
    sa.Column('participants', sa.Enum('MPO', 'MPO and MPP', 'MPO and supervisor', 'MPO, MPP and supervisor', name='adaptation_participants'), nullable=True),
    sa.Column('delay_reason', sa.Enum('Employee absent', 'Supervisor absent', 'MPO absent', 'MPP absent', 'Schedule conflict', 'Technical issues', 'High workload', 'Adaptation rescheduled', 'Other', name='adaptation_delay_reason'), nullable=True),
    sa.Column('risk_zone', sa.Enum('Green', 'Yellow', 'Red', name='risk_zone'), nullable=True),
    sa.Column('risk_reason', sa.Enum('Low performance', 'Insufficient skills', 'Low motivation', 'Attendance issues', 'Disciplinary issues', 'Difficulties working with the team', 'Difficulties working with the supervisor', 'Failure to meet adaptation goals', 'Other', name='adaptation_risk_reason'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('planned_end_date >= planned_start_date', name='ck_adaptation_stage_planned_dates'),
    sa.CheckConstraint('stage_number >= 1 AND stage_number <= 3', name='ck_adaptation_stage_number'),
    sa.ForeignKeyConstraint(['adaptation_process_id'], ['adaptation_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adaptation_process_id', 'stage_number', name='uq_adaptation_process_stage')
    )
    op.create_index(op.f('ix_adaptation_stages_adaptation_process_id'), 'adaptation_stages', ['adaptation_process_id'], unique=False)
    op.drop_index(op.f('ix_adaptations_employee_id'), table_name='adaptations')
    op.drop_table('adaptations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('adaptation_date', sa.DATE(), nullable=False),
    sa.Column('stage_number', sa.INTEGER(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=12), nullable=True),
    sa.Column('participants', sa.VARCHAR(length=23), nullable=False),
    sa.Column('delay_reason', sa.VARCHAR(length=22), nullable=True),
    sa.Column('risk_zone', sa.VARCHAR(length=6), nullable=True),
    sa.Column('risk_reason', sa.VARCHAR(length=40), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=256), nullable=True),
    sa.CheckConstraint('stage_number >= 1 AND stage_number <= 3', name=op.f('ck_adaptations_stage_number')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'stage_number', name=op.f('uq_adaptations_employee_stage'))
    )
    op.create_index(op.f('ix_adaptations_employee_id'), 'adaptations', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_adaptation_stages_adaptation_process_id'), table_name='adaptation_stages')
    op.drop_table('adaptation_stages')
    op.drop_index(op.f('ix_adaptation_processes_policy_id'), table_name='adaptation_processes')
    op.drop_index(op.f('ix_adaptation_processes_introductory_process_id'), table_name='adaptation_processes')
    op.drop_table('adaptation_processes')
    op.drop_index(op.f('ix_adaptation_policies_position_category'), table_name='adaptation_policies')
    op.drop_table('adaptation_policies')
    # ### end Alembic commands ###
