"""add data import journal

Revision ID: c06c07434b77
Revises: faf212000a95
Create Date: 2026-09-17 12:38:01.390016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06c07434b77'
down_revision: Union[str, Sequence[str], None] = 'faf212000a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Enum('onboarding_history', name='import_type'), nullable=False),
    sa.Column('status', sa.Enum('validating', 'ready', 'importing', 'completed', 'failed', name='import_status'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_created_by_user_id'), 'import_jobs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_file_hash'), 'import_jobs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_import_jobs_import_type'), 'import_jobs', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('import_job_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('excel_row_number', sa.Integer(), nullable=False),
    sa.Column('source_row_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('valid', 'warning', 'error', 'imported', 'skipped', name='import_row_status'), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_job_id', 'excel_row_number', name='uq_import_job_excel_row')
    )
    op.create_index(op.f('ix_import_job_rows_import_job_id'), 'import_job_rows', ['import_job_id'], unique=False)
    op.create_index('ix_import_job_rows_job_status', 'import_job_rows', ['import_job_id', 'status'], unique=False)
    op.create_index(op.f('ix_import_job_rows_status'), 'import_job_rows', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_import_job_rows_status'), table_name='import_job_rows')
    op.drop_index('ix_import_job_rows_job_status', table_name='import_job_rows')
    op.drop_index(op.f('ix_import_job_rows_import_job_id'), table_name='import_job_rows')
    op.drop_table('import_job_rows')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_import_type'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_file_hash'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_created_by_user_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
